from tvtk.api import tvtk
s = tvtk.CubeSource(x_length=1.0, y_length=2.0, z_length=3.0)
m=tvtk.PolyDataMapper(input_connection=s.output_port)
a = tvtk.Actor(mapper = m)
s2 = tvtk.SoneSource(height=3.0, radius=1.0, resolution=36)
s2.center=(4,4,4)
m2=tvtk.PolyDataMapper(input_connection=s2.output_port)
a2 = tvtk.Actor(mapper = m2)
r = tvtk.Renderer(background=(0.3, 0.3, 0.3))
r.add_actor(a)
r.add_actor(a2)
w = tvtk.RenderWindow(size=(300,300))
w.add_renderer(r)
i = tvtk.RenderWindowInteractor(render_window=w)
i.initialize()
i.start()
